POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name": "prueba",
    "email": "pr@hm.com",
    "password": "123456"
}


### login sin conexion a BDD

POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name": "prueba2",
    "email": "pr@hm.com",
    "password": "1234567"

}

### users
GET http://127.0.0.1:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MzI3NTI0MTksImV4cCI6MTczMjc1MjQ3OX0.da8qrLwKt4STN7POeJjstZy0pC3eZW2HcXdJpIZt65c


